DROP TABLE MOVIEBOARD;
DROP SEQUENCE MOVIEBOARDSEQ;


CREATE SEQUENCE MOVIEBOARDSEQ NOCACHE;
CREATE TABLE MOVIEBOARD(
	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(200) NOT NULL,
	TITLE VARCHAR2(2000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL

);

