-- MOVIE_CATEGORY 테이블 
DROP TABLE MOVIE_CATEGORY;

CREATE TABLE MOVIE_CATEGORY(
	MOVIE_TYPE NUMBER PRIMARY KEY,
	MOVIE_TYPE_NAME VARCHAR2(200) NOT NULL
);	

INSERT INTO MOVIE_CATEGORY VALUES(1, '액션');
INSERT INTO MOVIE_CATEGORY VALUES(2, '공포/스릴러');
INSERT INTO MOVIE_CATEGORY VALUES(3, 'SF/판타지');
INSERT INTO MOVIE_CATEGORY VALUES(4, '드라마/로맨스');
INSERT INTO MOVIE_CATEGORY VALUES(5, '다큐멘터리');
INSERT INTO MOVIE_CATEGORY VALUES(6, '애니메이션');

COMMIT;

SELECT * FROM MOVIE_CATEGORY;



-- MOVIE_BOARD 테이블
DROP TABLE MOVIE_BOARD;
DROP SEQUENCE MOVIE_BOARDSEQ;

CREATE SEQUENCE MOVIE_BOARDSEQ NOCACHE;
CREATE TABLE MOVIE_BOARD(
MOVIE_ID NUMBER PRIMARY KEY,
MOVIE_TYPE NUMBER NOT NULL,
MOVIE_TITLE VARCHAR2(400) NOT NULL,
DIRECTOR VARCHAR2(200) NOT NULL,
ACTOR VARCHAR2(1000) NOT NULL,
PARTICIPANT NUMBER NOT NULL,
MOVIE_IMG VARCHAR2(400) NOT NULL,
CREATEAT DATE  NOT NULL,
UPDATEAT DATE  NOT NULL,

CONSTRAINT FK_MOIVE_TYPE FOREIGN KEY (MOVIE_TYPE) REFERENCES MOVIE_CATEGORY(MOVIE_TYPE)
);
--TEST 데이터
INSERT INTO MOVIE_BOARD VALUES(MOVIE_BOARDSEQ.NEXTVAL, 1, '엑시트', '장항준', '조정석', 10, '텍스트이미지', SYSDATE, SYSDATE);

COMMIT;


SELECT * FROM MOVIE_BOARD;


-- MOVIE_REVIEW 테이블

DROP TABLE MOVIE_REVIEW;
DROP SEQUENCE MOVIE_REVIEWSEQ;

CREATE SEQUENCE MOVIE_REVIEWSEQ NOCACHE;

CREATE TABLE MOVIE_REVIEW(
REVIEW_ID NUMBER PRIMARY KEY,
NICKNAME VARCHAR2(400) NOT NULL,
MOVIE_ID NUMBER NOT NULL,
REVIEW_TITLE VARCHAR2(400) NOT NULL,
REVIEW_CONTENT VARCHAR2(2000) NOT NULL,
MOIVE_GRADE NUMBER NOT NULL,
REVIEW_R_NUM NUMBER NOT NULL,
REVIEW_V_NUM NUMBER NOT NULL,
REVIEW_IMG VARCHAR2(400) NOT NULL,
STATUS_NO NUMBER NOT NULL,
DELETE_N NUMBER NOT NULL,
CREATEAT DATE NOT NULL,
UPDATEAT DATE NOT NULL,

CONSTRAINT FK_NICKNAME FOREIGN KEY (NICKNAME) REFERENCES MEMBER(NICKNAME),
CONSTRAINT FK_MOVIE_ID FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE_BOARD(MOVIE_ID)
);

--TEST 데이터
INSERT INTO MOVIE_REVIEW VALUES(MOVIE_REVIEWSEQ.NEXTVAL, 'seungjune@naver.com', 2, '테스트 제목입니다','가나마라마바사',10 ,
0,1,'텍스트이미지', 1,1,SYSDATE,SYSDATE);

COMMIT;

SELECT * FROM MOVIE_REVIEW;


