DROP TABLE MEMBER_LEVEL CASCADE CONSTRAINTS;
DROP TABLE MEMBER_STATUS CASCADE CONSTRAINTS;
DROP TABLE MEMBER CASCADE CONSTRAINTS;

--유저 레벨 테이블
CREATE TABLE MEMBER_LEVEL(
    LEVEL_NO NUMBER PRIMARY KEY,
    LEVEL_NAME VARCHAR2(30) NOT NULL
);

INSERT INTO MEMBER_LEVEL VALUES(1, '정관리자');
INSERT INTO MEMBER_LEVEL VALUES(2, '부관리자');
INSERT INTO MEMBER_LEVEL VALUES(3, '회원');

SELECT * FROM MEMBER_LEVEL;

--유저 상태 테이블
CREATE TABLE MEMBER_STATUS(
    STATUS_NO NUMBER PRIMARY KEY,
    STATUS_NAME VARCHAR2(30) NOT NULL
);

INSERT INTO MEMBER_STATUS VALUES(1, '활동');
INSERT INTO MEMBER_STATUS VALUES(2, '정지');
INSERT INTO MEMBER_STATUS VALUES(3, '탈퇴');

SELECT * FROM MEMBER_STATUS;


--유저 테이블
CREATE TABLE MEMBER(
    EMAIL VARCHAR2(100) PRIMARY KEY,
    NICKNAME VARCHAR2(100) UNIQUE NOT NULL,
    LEVEL_NO NUMBER NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    BIRTH VARCHAR2(100) NOT NULL,
    GENDER VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    ADDRESS_DETAIL VARCHAR2(200) NOT NULL,
    CREATE_AT DATE NOT NULL,
    UPDATE_AT DATE NOT NULL,
    STATUS_NO NUMBER NOT NULL,
    
    CONSTRAINT M_LEVEL FOREIGN KEY(LEVEL_NO) REFERENCES MEMBER_LEVEL(LEVEL_NO),
    CONSTRAINT STATUS FOREIGN KEY(STATUS_NO) REFERENCES MEMBER_STATUS(STATUS_NO)
);

ALTER TABLE MEMBER ADD EMAIL_HASH VARCHAR2(1000);
INSERT INTO MEMBER_STATUS VALUES(4, '미인증');

INSERT INTO MEMBER(EMAIL, NICKNAME, LEVEL_NO, PASSWORD, NAME, BIRTH, GENDER, CREATE_AT, UPDATE_AT, STATUS_NO, ADDRESS, ADDRESS_DETAIL, EMAIL_HASH) 
VALUES('admin@allreview.com', '정관리자', 1, 'admin1234', '관리자', '2021-07-14', '남자', SYSDATE, SYSDATE, 1, '관리자 주소는 없습니다', '관리자 주소는 없습니다', '인증불필요');
INSERT INTO MEMBER(EMAIL, NICKNAME, LEVEL_NO, PASSWORD, NAME, BIRTH, GENDER, CREATE_AT, UPDATE_AT, STATUS_NO, ADDRESS, ADDRESS_DETAIL, EMAIL_HASH) 
VALUES('admin2@allreview.com', '부관리자', 2, 'admin1234', '부관리자', '2021-07-14', '여자', SYSDATE, SYSDATE, 1, '관리자 주소는 없습니다', '관리자 주소는 없습니다', '인증불필요');
INSERT INTO MEMBER(EMAIL, NICKNAME, LEVEL_NO, PASSWORD, NAME, BIRTH, GENDER, CREATE_AT, UPDATE_AT, STATUS_NO, ADDRESS, ADDRESS_DETAIL, EMAIL_HASH) 
VALUES('user1@allreview.com', '회원1', 3, 'admin1234', '회원1별명', '2021-07-14', '남자', SYSDATE, SYSDATE, 1, '서울 어딘가', '살고 있네요', '인증불필요');
INSERT INTO MEMBER(EMAIL, NICKNAME, LEVEL_NO, PASSWORD, NAME, BIRTH, GENDER, CREATE_AT, UPDATE_AT, STATUS_NO, ADDRESS, ADDRESS_DETAIL, EMAIL_HASH) 
VALUES('user2@allreview.com', '회원2', 3, 'admin1234', '회원2별명', '2021-07-14', '남자', SYSDATE, SYSDATE, 1, '서울 어딘가', '살고 있네요', '인증불필요');
INSERT INTO MEMBER(EMAIL, NICKNAME, LEVEL_NO, PASSWORD, NAME, BIRTH, GENDER, CREATE_AT, UPDATE_AT, STATUS_NO, ADDRESS, ADDRESS_DETAIL, EMAIL_HASH) 
VALUES('user3@allreview.com', '회원3', 3, 'admin1234', '회원3별명', '2021-07-14', '여자', SYSDATE, SYSDATE, 1, '서울 어딘가', '살고 있네요', '인증불필요');
SELECT * FROM MEMBER;

