--유저 레벨 테이블
CREATE TABLE MEMBER_LEVEL(
    LEVEL_NO NUMBER PRIMARY KEY,
    LEVEL_NAME VARCHAR2(30) NOT NULL
);

INSERT INTO MEMBER_LEVEL VALUES(1, '정관리자');
INSERT INTO MEMBER_LEVEL VALUES(2, '부관리자');
INSERT INTO MEMBER_LEVEL VALUES(3, '회원');

SELECT * FROM MEMBER_LEVEL;

--유저 상태 테이블
CREATE TABLE MEMBER_STATUS(
    STATUS_NO NUMBER PRIMARY KEY,
    STATUS_NAME VARCHAR2(30) NOT NULL
);

INSERT INTO MEMBER_STATUS VALUES(1, '활동');
INSERT INTO MEMBER_STATUS VALUES(2, '정지');
INSERT INTO MEMBER_STATUS VALUES(3, '탈퇴');

SELECT * FROM MEMBER_STATUS;


--유저 테이블
CREATE TABLE MEMBER(
    EMAIL VARCHAR2(100) PRIMARY KEY,
    NICKNAME VARCHAR2(100) UNIQUE NOT NULL,
    LEVEL_NO NUMBER NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100) NOT NULL,
    BIRTH VARCHAR2(100) NOT NULL,
    GENDER VARCHAR2(20) NOT NULL,
    ADDRESS VARCHAR2(200) NOT NULL,
    ADDRESS_DETAIL VARCHAR2(200) NOT NULL,
    CREATE_AT DATE NOT NULL,
    UPDATE_AT DATE NOT NULL,
    STATUS_NO NUMBER NOT NULL,
    
    CONSTRAINT M_LEVEL FOREIGN KEY(LEVEL_NO) REFERENCES MEMBER_LEVEL(LEVEL_NO),
    CONSTRAINT STATUS FOREIGN KEY(STATUS_NO) REFERENCES MEMBER_STATUS(STATUS_NO)
);

ALTER TABLE MEMBER ADD EMAIL_HASH VARCHAR2(1000);
INSERT INTO MEMBER_STATUS VALUES(4, '미인증');

SELECT * FROM MEMBER;

